FROM python:3.10-alpine3.18

WORKDIR /app
COPY requirements.txt .
COPY app_service app_service
RUN pip install -r requirements.txt

EXPOSE 5000
CMD ["python", "app_service/main.py", "-b", "0.0.0.0:5000", "-t", "300"]
#Execute com: docker run --rm -p 5000:5000 image_name
#faça o post no http://127.0.0.1:5000/mesage_request


